name: CLI GraalVM Native Image Builds - Copy
#on: [push, pull_request]
on:
  push:
    branches: ["CNDIT-538-dataingestion-cli"]
    tags:
      - 'v*'
  pull_request:
    branches: ["CNDIT-538-dataingestion-cli"]
    tags:
      - 'v*'
jobs:
  build:
    name: Data Ingestion CLI build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

#      - name: CLI Native Image build using gradle
#        run: ./gradlew nativeCompile

#      - uses: actions/checkout@v3
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Get current date and time
        run: echo "DATE_TIME=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}-${{ env.DATE_TIME }}
          release_name: Release ${{ github.ref_name }}-${{ matrix.os }}-${{ env.DATE_TIME }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/native/nativeCompile/
          asset_name: NEDSS-DataIngestion-CLI*

      - name: Archive binary image asset
        uses: actions/upload-artifact@v3
        with:
          name: NEDSS-DataIngestion-CLI
          path: build/native/nativeCompile/
